# 沙箱账号
aliPay:
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  appID: 2016091400508498
  merchantPrivateKey:  #支付宝私钥
  aliPayPublicKey:  #支付宝公钥
  returnUrl: http://s9v2cw.natappfree.cc/alipay/return   #回调通知地址根据自己要求填写
  notifyUrl: http://s9v2cw.natappfree.cc/alipay/notify   #异步回调地址根据自己要求填写
  sysServiceProviderId: 2088431933571493
  signType: RSA2
  charset: utf-8
